# create new Room
POST http://localhost:3001/api/v1/rooms/admin HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzFjM2ZlOGVkMTkzOTgxYzM0YzQ3Y2UiLCJlbWFpbCI6Im5oYW5ubjg3ZG5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY0NTA5MDA4fQ.s6uTYu1lONG2VEuV_XFzSC6UkqWAnoY8zZEjFoF73b8

{
    "name": "Standard Single Room",
    "metaTitle": "Standard Single Room best Price",
    "metaDescription": "Standard Single Rooms are designed in open-concept living area and have many facilities. Best Price. Booking now !",
    "pricePerNight": 29,
    "priceChildren": 75,
    "content": "Standard Single Rooms are designed in open-concept living area and have many facilities",
    "guestCapacity": 2,
    "numOfBeds": 1,
    "typeOfBeds": "Single",
    "area": "20m2",
    "ratings": 4,
    "numOfReviews": 10,
    "category" : "Single",
    "user": "631c3fe8ed193981c34c47ce"
}

###

POST /api/v1/rooms/admin HTTP/1.1
Host: localhost:3001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzFjM2ZlOGVkMTkzOTgxYzM0YzQ3Y2UiLCJlbWFpbCI6Im5oYW5ubjg3ZG5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY0NTA5MDA4fQ.s6uTYu1lONG2VEuV_XFzSC6UkqWAnoY8zZEjFoF73b8
Content-Length: 378
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"
Content-Type: application/json

Standard Single Room
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="/C:/xampp/htdocs/learning/Hotel-Booking/client/public/images/gallery/g1.jpg"
Content-Type: image/jpeg

(data)
----WebKitFormBoundary7MA4YWxkTrZu0gW